# Generated by pi/kit/bin/arc-waypoints.mjs -- do not hand-edit.
# The chrome's hue arc, sampled 12 times from its cold end to its warm one:
# blue, indigo, violet, magenta, pink, coral, red, gold, yellow, green. The one
# thing it never reaches is the wedge from green back round to blue -- teal,
# cyan, sky -- which is what keeps it reading as one light rather than as a
# rainbow.
#
# A fact about the arc, so no timing appears here: how fast a light walks it,
# and how much of it is on screen at once, is the caller's business.
# Regenerate from the pi kit after changing HUE_MIN, HUE_MAX or the surfaces in
# extensions/zen-chrome/prism.ts.
ARC_DARK=(0xff5c82f2 0xff755cf2 0xffb45cf2 0xfff25cf2 0xfff25cb4 0xfff25c75 0xfff2825c 0xfff2c05c 0xffe6f25c 0xffa7f25c 0xff69f25c 0xff5cf28e)
ARC_LIGHT=(0xff4e6dcc 0xff634ecc 0xff974ecc 0xffcc4ecc 0xffcc4e97 0xffcc4e63 0xffcc6d4e 0xffcca24e 0xffc1cc4e 0xff8dcc4e 0xff58cc4e 0xff4ecc78)
ARC_POINTS=12
